# 菜单配置
main:
  - name: "首页"
    url: "/"
    weight: 1

  - name: "化学式转LaTeX"
    url: "/convert_latex/"
    weight: 2

  - name: "博客与文章"
    url: "/posts/"
    weight: 3

  - name: "分类导航"
    url: "/categories/"
    weight: 4

  - name: "标签"
    url: "/tags/"
    weight: 5

  - name: "测试(预留化学式配平)"
    url: "/tags/"
    weight: 6

  - name: "测试(预留元素性质)"
    url: "/tags/"
    weight: 7

  - name: "关于我们"
    url: "/about/"
    weight: 10

  - name: "联系方式"
    url: "/contact/"
    weight: 11
