# 菜单配置
main:
  - name: "首页"
    url: "/"
    weight: 1

  - name: "化学式转LaTeX"
    url: "/convert_latex/"
    weight: 2

  - name: "溶液浓度计算"
    url: "/calc_concentration/"
    weight: 3

  - name: "体积分数计算"
    url: "/calc_volume/"
    weight: 4

  - name: "博客与文章"
    url: "/posts/"
    weight: 10

  - name: "分类导航"
    url: "/categories/"
    weight: 11

  - name: "标签"
    url: "/tags/"
    weight: 12


  - name: "关于我们"
    url: "/about/"
    weight: 20

  - name: "联系方式"
    url: "/contact/"
    weight: 21
